version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data
    environment:
      - OLLAMA_HOST=ollama
      - PYTHONPATH=/app
    depends_on:
      ollama:
        condition: service_healthy

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: sh -c "ollama serve & sleep 10 && ollama pull llama2 && tail -f /dev/null"

volumes:
  ollama_data: 